services:
  merlinai-adapter-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merlinai-adapter-server
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
